declare module "@env" {
    export const LINK_NAMED_POLICY: string;
    export const LINK_USING_TERM: string;
    export const LINK_SOCIAL_TERM: string;
    export const LINK_REGISTER_POST: string;
    export const LINK_UPDATE_IMAGE:string;
    export const SQLITE_DB_NAME: string;
    export const LINK_SIGN_IN_ENCRYPT: string;
    export const LINK_CREATE_OTP: string;
    export const LINK_VERTIFY_OTP: string;
    export const LINK_OPEN_CONVERSATION: string;
    export const LINK_GET_MESSAGE_HISTORY: string;
    export const LINK_SEND_MESSAGE: string;
    export const LINK_SEARCH_USER: string;
    export const LINK_GET_MY_FRIENDS: string;
    export const LINK_REQUEST_ADD_FRIEND : string;
    export const LINK_ACCEPT_FRIEND_REQUEST : string;
    export const LINK_REQUEST_FRIEND_LIST : string;
    export const LINK_REVOCATION_REQUEST_FRIEND : string;
    export const LINK_GET_MY_CONVERSATIONS: string;
    export const LINK_SOCKET_IO: string;
    export const LINK_REQUEST_FRIEND_WAIT_RESPONSE: string;
    export const LINK_GET_FRIEND_REQUEST: string;
    export const LINK_GET_ADD_FRIEND_ACCEPT: string;
    export const LINK_GET_ADD_FRIEND_REJECT: string;
    export const LINK_DELETE_MESSAGE_SIDE_ME: string;
    export const LINK_DELETE_MESSAGE_SIDE_ALL: string;
    export const LINK_PIN_MESSAGE: string;
    export const LINK_UNPIN_MESSAGE: string;
    export const LINK_REACT_MESSAGE: string;
    export const LINK_FORWARD_MESSAGE: string;
    export const LINK_GROUP: string;
}